print('===== DESAFIO 4 =====')
x = input('Digite alguma coisa: ')
print(type(x))
print('É uma string Alfabética?: ')
print(x.isalpha())
print('É um numero?: ')
print(x.isnumeric())
print('É um alfanumérico?: ')
print(x.isalnum())
